apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: lab-flask-bdd
build:
  artifacts:
    - image: lab-flask-bdd
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/pv.yaml
    - k8s/postgresql.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/ingress.yaml
