apiVersion: v1
kind: Service
metadata:
  name: lab-flask-bdd
spec:
  selector:
    app: lab-flask-bdd
  type: ClusterIP
  internalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
